# fly.toml app configuration file generated for starcite-staging-0220f on 2026-02-21T09:42:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'starcite-staging-0220f'
primary_region = 'lhr'
kill_signal = 'SIGTERM'
kill_timeout = '30s'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  strategy = 'immediate'

[env]
  PHX_SERVER = 'true'
  PORT = '4000'
  STARCITE_ARCHIVE_ADAPTER = 's3'
  STARCITE_ARCHIVE_FLUSH_INTERVAL_MS = '3600000'
  STARCITE_S3_BUCKET = 'starcite-staging-archive'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '1m0s'
    method = 'get'
    path = '/health/live'

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '1m0s'
    method = 'get'
    path = '/health/ready'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1024mb'
